version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: vg-mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=institution2025
      - MONGO_INITDB_DATABASE=vg_ms_institution
    networks:
      - vg-network

  vg-ms-institution:
    image: vg-ms-institution:latest
    container_name: vg-ms-institution
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=vg_ms_institution
      - MONGO_USER=admin
      - MONGO_PASSWORD=institution2025
    depends_on:
      - mongodb
    networks:
      - vg-network

volumes:
  mongodb_data:
    driver: local

networks:
  vg-network:
    driver: bridge